name: Build Mods

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '6.0.x'

    - name: Add reference assemblies
      uses: Pathoschild/SMAPI-ModBuildWorkflow/add-reference-assemblies@v0

    - name: Detect changed projects
      id: detect
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          BEFORE_SHA=${{ github.event.before }}
          AFTER_SHA=${{ github.sha }}
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          BEFORE_SHA=${{ github.event.pull_request.base.sha }}
          AFTER_SHA=${{ github.event.pull_request.head.sha }}
        else
          echo "Unsupported event ${{ github.event_name }}"
          exit 1
        fi
        CHANGED=$(git diff --name-only $BEFORE_SHA $AFTER_SHA | cut -d'/' -f1 | sort | uniq)
        VALID_PROJECTS=()
        for proj in $CHANGED; do
          if [ -f "$proj/$proj.csproj" ]; then
            VALID_PROJECTS+=($proj)
          fi
          
        done
        echo "Changed projects: $VALID_PROJECTS"
        echo "changed_projects=$VALID_PROJECTS" >> $GITHUB_OUTPUT

    - name: Build and zip changed projects
      run: |
        for proj in ${{ steps.detect.outputs.changed_projects }}; do
          if [ -f "$proj/$proj.csproj" ]; then
            echo "Building $proj..."
            dotnet restore "$proj/$proj.csproj"
            dotnet build "$proj/$proj.csproj" --configuration Release --no-restore

            echo "Zipping $proj..."
            mkdir -p ./artifacts/$proj
            mv "$proj/bin/Release/net6.0/*.zip" ./artifacts/
          else
            echo "Skipping $proj, no csproj found"
          fi
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Project-Mod-ZIP
        path: ./artifacts/**
